
export const ErrorCodeEnum = {
    ORGANIZATION_ALREADY_EXISTS: "ORGANIZATION_ALREADY_EXISTS",
    ORGANIZATION_USER_LIMIT_EXCEEDED: "ORGANIZATION_USER_LIMIT_EXCEEDED",


    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_USER_ALREADY_EXISTS: "AUTH_USER_ALREADY_EXISTS",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
    AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
    AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
    AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
    AUTH_PASSWORD_INVALID: "AUTH_PASSWORD_INVALID",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
    ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;